version: "3.9"

services:
  ai-interview:
    container_name: ai-interview
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3190:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NITRO_PORT: 3000
      NITRO_HOST: 0.0.0.0
